feature/v2.8.3
mx51/spi-client-js pull request #112
Opened 2021-05-27 23:18 UTC by mattgresham

- Bump library version
- Bump vulnerable packages
- Add the ability to report Spice version (SP-677)
- Fix test not waiting for promise to complete before continuing

2021-06-07 23:54 UTC, RaymondK-mx51 requested changes

2021-06-07 23:54 UTC, RaymondK-mx51 commented on src/Spi.js
> +    ResendPosInfo()
We have a `SetPosInfo` and a `ResendPosInfo` both are public functions and they both have same purpose but executed differently. 

As someone integrating with the function, which one would I use? When would I use ResendPosInfo?

2021-06-08 01:30 UTC, RaymondK-mx51 commented on src/Spi.js
> +    ResendPosInfo()
As discussed on Zoom

Can you please rename `ResendPosInfo` to `SetAdaptorPosInfo` and `SetSpiceInfo` to `SetAdaptorInfo`

2021-06-08 01:54 UTC, mattgresham commented on src/Spi.js
> +    ResendPosInfo()
Updated!

2021-06-08 03:15 UTC, RaymondK-mx51 approved these changes

2021-06-08 03:16 UTC, RaymondK-mx51 commented
Thanks Matt!

2021-06-08 05:03 UTC, merged